/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOLINK__DRIVER_MSGS__POWERSTATE_PROTO_DRIVER_MSGS__POWERSTATE_PB_H_INCLUDED
#define PB_PROTOLINK__DRIVER_MSGS__POWERSTATE_PROTO_DRIVER_MSGS__POWERSTATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time {
    bool has_sec;
    int32_t sec;
    bool has_nanosec;
    uint32_t nanosec;
} protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time;

typedef struct _protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header {
    bool has_stamp;
    protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time stamp;
    pb_callback_t frame_id;
} protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header;

typedef struct _protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status {
    bool has_id;
    uint32_t id;
} protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status;

typedef struct _protolink__driver_msgs__PowerState_driver_msgs__PowerState {
    bool has_header;
    protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header header;
    bool has_status;
    protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status status;
    bool has_log_voltage;
    float log_voltage;
    bool has_log_current;
    float log_current;
    bool has_log_power;
    float log_power;
    bool has_act_voltage;
    float act_voltage;
    bool has_act_current;
    float act_current;
    bool has_act_power;
    float act_power;
    bool has_log_temp;
    float log_temp;
    bool has_act_temp;
    float act_temp;
} protolink__driver_msgs__PowerState_driver_msgs__PowerState;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_init_default {false, protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_init_default, false, protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_init_default, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_init_default {false, protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_init_default, {{NULL}, NULL}}
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_init_default {false, 0, false, 0}
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_init_default {false, 0}
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_init_zero {false, protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_init_zero, false, protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_init_zero, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_init_zero {false, protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_init_zero, {{NULL}, NULL}}
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_init_zero {false, 0, false, 0}
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_init_zero {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_sec_tag 1
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_nanosec_tag 2
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_stamp_tag 1
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_frame_id_tag 2
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_id_tag 1
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_header_tag 1
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_status_tag 2
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_log_voltage_tag 3
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_log_current_tag 4
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_log_power_tag 5
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_act_voltage_tag 6
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_act_current_tag 7
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_act_power_tag 8
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_log_temp_tag 9
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_act_temp_tag 10

/* Struct field encoding specification for nanopb */
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            2) \
X(a, STATIC,   OPTIONAL, FLOAT,    log_voltage,       3) \
X(a, STATIC,   OPTIONAL, FLOAT,    log_current,       4) \
X(a, STATIC,   OPTIONAL, FLOAT,    log_power,         5) \
X(a, STATIC,   OPTIONAL, FLOAT,    act_voltage,       6) \
X(a, STATIC,   OPTIONAL, FLOAT,    act_current,       7) \
X(a, STATIC,   OPTIONAL, FLOAT,    act_power,         8) \
X(a, STATIC,   OPTIONAL, FLOAT,    log_temp,          9) \
X(a, STATIC,   OPTIONAL, FLOAT,    act_temp,         10)
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_CALLBACK NULL
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_DEFAULT NULL
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_header_MSGTYPE protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_status_MSGTYPE protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status

#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stamp,             1) \
X(a, CALLBACK, OPTIONAL, STRING,   frame_id,          2)
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_CALLBACK pb_default_field_callback
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_DEFAULT NULL
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_stamp_MSGTYPE protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time

#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    sec,               1) \
X(a, STATIC,   OPTIONAL, UINT32,   nanosec,           2)
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_CALLBACK NULL
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_DEFAULT NULL

#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1)
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_CALLBACK NULL
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_DEFAULT NULL

extern const pb_msgdesc_t protolink__driver_msgs__PowerState_driver_msgs__PowerState_msg;
extern const pb_msgdesc_t protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_msg;
extern const pb_msgdesc_t protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_msg;
extern const pb_msgdesc_t protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_fields &protolink__driver_msgs__PowerState_driver_msgs__PowerState_msg
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_fields &protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_msg
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_fields &protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_msg
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_fields &protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_msg

/* Maximum encoded size of messages (where known) */
/* protolink__driver_msgs__PowerState_driver_msgs__PowerState_size depends on runtime parameters */
/* protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_size depends on runtime parameters */
#define PROTOLINK__DRIVER_MSGS__POWERSTATE_PROTO_DRIVER_MSGS__POWERSTATE_PB_H_MAX_SIZE protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_size
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_common_msgs__Status_size 6
#define protolink__driver_msgs__PowerState_driver_msgs__PowerState_std_msgs__Header_builtin_interfaces__Time_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
