/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOLINK__DRIVER_MSGS__RTCTIME_PROTO_DRIVER_MSGS__RTCTIME_PB_H_INCLUDED
#define PB_PROTOLINK__DRIVER_MSGS__RTCTIME_PROTO_DRIVER_MSGS__RTCTIME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time {
    bool has_sec;
    int32_t sec;
    bool has_nanosec;
    uint32_t nanosec;
} protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time;

typedef struct _protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header {
    bool has_stamp;
    protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time stamp;
    pb_callback_t frame_id;
} protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header;

typedef struct _protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status {
    bool has_id;
    uint32_t id;
} protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status;

typedef struct _protolink__driver_msgs__RtcTime_driver_msgs__RtcTime {
    bool has_header;
    protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header header;
    bool has_status;
    protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status status;
    bool has_year;
    uint32_t year;
    bool has_month;
    uint32_t month;
    bool has_day;
    uint32_t day;
    bool has_hour;
    uint32_t hour;
    bool has_minute;
    uint32_t minute;
    bool has_second;
    uint32_t second;
} protolink__driver_msgs__RtcTime_driver_msgs__RtcTime;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_init_default {false, protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_init_default, false, protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_init_default, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_init_default {false, protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_init_default, {{NULL}, NULL}}
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_init_default {false, 0, false, 0}
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_init_default {false, 0}
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_init_zero {false, protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_init_zero, false, protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_init_zero, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_init_zero {false, protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_init_zero, {{NULL}, NULL}}
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_init_zero {false, 0, false, 0}
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_init_zero {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_sec_tag 1
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_nanosec_tag 2
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_stamp_tag 1
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_frame_id_tag 2
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_id_tag 1
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_header_tag 1
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_status_tag 2
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_year_tag 3
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_month_tag 4
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_day_tag 5
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_hour_tag 6
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_minute_tag 7
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_second_tag 8

/* Struct field encoding specification for nanopb */
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   year,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   month,             4) \
X(a, STATIC,   OPTIONAL, UINT32,   day,               5) \
X(a, STATIC,   OPTIONAL, UINT32,   hour,              6) \
X(a, STATIC,   OPTIONAL, UINT32,   minute,            7) \
X(a, STATIC,   OPTIONAL, UINT32,   second,            8)
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_CALLBACK NULL
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_DEFAULT NULL
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_header_MSGTYPE protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_status_MSGTYPE protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status

#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stamp,             1) \
X(a, CALLBACK, OPTIONAL, STRING,   frame_id,          2)
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_CALLBACK pb_default_field_callback
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_DEFAULT NULL
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_stamp_MSGTYPE protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time

#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    sec,               1) \
X(a, STATIC,   OPTIONAL, UINT32,   nanosec,           2)
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_CALLBACK NULL
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_DEFAULT NULL

#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1)
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_CALLBACK NULL
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_DEFAULT NULL

extern const pb_msgdesc_t protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_msg;
extern const pb_msgdesc_t protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_msg;
extern const pb_msgdesc_t protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_msg;
extern const pb_msgdesc_t protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_fields &protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_msg
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_fields &protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_msg
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_fields &protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_msg
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_fields &protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_msg

/* Maximum encoded size of messages (where known) */
/* protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_size depends on runtime parameters */
/* protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_size depends on runtime parameters */
#define PROTOLINK__DRIVER_MSGS__RTCTIME_PROTO_DRIVER_MSGS__RTCTIME_PB_H_MAX_SIZE protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_size
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status_size 6
#define protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
