/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "proto/driver_msgs__RtcGnss.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss, protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss, AUTO)


PB_BIND(protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header, protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header, AUTO)


PB_BIND(protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time, protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time, AUTO)


PB_BIND(protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status, protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

