/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOLINK__DRIVER_MSGS__RTCGNSS_PROTO_DRIVER_MSGS__RTCGNSS_PB_H_INCLUDED
#define PB_PROTOLINK__DRIVER_MSGS__RTCGNSS_PROTO_DRIVER_MSGS__RTCGNSS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time {
    bool has_sec;
    int32_t sec;
    bool has_nanosec;
    uint32_t nanosec;
} protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time;

typedef struct _protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header {
    bool has_stamp;
    protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time stamp;
    pb_callback_t frame_id;
} protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header;

typedef struct _protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status {
    bool has_id;
    uint32_t id;
} protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status;

typedef struct _protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss {
    bool has_header;
    protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header header;
    bool has_status;
    protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status status;
    bool has_latitude;
    double latitude;
    bool has_longitude;
    double longitude;
    bool has_altitude;
    float altitude;
    bool has_satellites;
    int32_t satellites;
} protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_init_default {false, protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_init_default, false, protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_init_default, false, 0, false, 0, false, 0, false, 0}
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_init_default {false, protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_init_default, {{NULL}, NULL}}
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_init_default {false, 0, false, 0}
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_init_default {false, 0}
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_init_zero {false, protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_init_zero, false, protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_init_zero, false, 0, false, 0, false, 0, false, 0}
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_init_zero {false, protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_init_zero, {{NULL}, NULL}}
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_init_zero {false, 0, false, 0}
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_init_zero {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_sec_tag 1
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_nanosec_tag 2
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_stamp_tag 1
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_frame_id_tag 2
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_id_tag 1
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_header_tag 1
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_status_tag 2
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_latitude_tag 3
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_longitude_tag 4
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_altitude_tag 5
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_satellites_tag 6

/* Struct field encoding specification for nanopb */
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            2) \
X(a, STATIC,   OPTIONAL, DOUBLE,   latitude,          3) \
X(a, STATIC,   OPTIONAL, DOUBLE,   longitude,         4) \
X(a, STATIC,   OPTIONAL, FLOAT,    altitude,          5) \
X(a, STATIC,   OPTIONAL, INT32,    satellites,        6)
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_CALLBACK NULL
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_DEFAULT NULL
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_header_MSGTYPE protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_status_MSGTYPE protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status

#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stamp,             1) \
X(a, CALLBACK, OPTIONAL, STRING,   frame_id,          2)
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_CALLBACK pb_default_field_callback
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_DEFAULT NULL
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_stamp_MSGTYPE protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time

#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    sec,               1) \
X(a, STATIC,   OPTIONAL, UINT32,   nanosec,           2)
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_CALLBACK NULL
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_DEFAULT NULL

#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1)
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_CALLBACK NULL
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_DEFAULT NULL

extern const pb_msgdesc_t protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_msg;
extern const pb_msgdesc_t protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_msg;
extern const pb_msgdesc_t protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_msg;
extern const pb_msgdesc_t protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_fields &protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_msg
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_fields &protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_msg
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_fields &protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_msg
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_fields &protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_msg

/* Maximum encoded size of messages (where known) */
/* protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_size depends on runtime parameters */
/* protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_size depends on runtime parameters */
#define PROTOLINK__DRIVER_MSGS__RTCGNSS_PROTO_DRIVER_MSGS__RTCGNSS_PB_H_MAX_SIZE protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_size
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_common_msgs__Status_size 6
#define protolink__driver_msgs__RtcGnss_driver_msgs__RtcGnss_std_msgs__Header_builtin_interfaces__Time_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
