/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "proto/driver_msgs__RtcTime.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protolink__driver_msgs__RtcTime_driver_msgs__RtcTime, protolink__driver_msgs__RtcTime_driver_msgs__RtcTime, AUTO)


PB_BIND(protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header, protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header, AUTO)


PB_BIND(protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time, protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_std_msgs__Header_builtin_interfaces__Time, AUTO)


PB_BIND(protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status, protolink__driver_msgs__RtcTime_driver_msgs__RtcTime_common_msgs__Status, AUTO)



